### ISSUE TITLE
[Bug]: Crash on manual tiling layout editing/occasionally on resize

### ISSUE THREAD

**Issue by firefoxfirefox** [zeroxoneafour/polonium#114] opened 2024-03-07 17:12 UTC
### Before you make the issue, confirm that

- [X] You are running the master build from GitHub actions
- [X] You have read the FAQ and the usage instructions
- [X] You have searched pull requests and issues and have found none similar to your issue
- [X] This problem comes from a failure in the tiling system and not a missing feature

### Describe the bug

I am using the plasma 6 kwinscript from 1.0b1. Whenever I edit the kwin layout manually be pressing delete or split horizontally, etc. wayland crashes. When this happens the screen turns black and all the apps crash and for some reason my icons only task manager gets reset to some previous state and isn't restored (the wrong apps are shown). This crash also happened twice when I was just resizing a window.

### To reproduce

Enable the polonium kwin script, try doing anything with manual layout editing. Crash is not reproducible with kwin script disabled.

### Expected behavior

Don't crash

### Relevant log output

```shell
Mar 07 12:08:29 HoldenComputer kwin_wayland[1254]: qml: Polonium INF: Polonium started!
Mar 07 12:08:29 HoldenComputer kwin_wayland[1254]: qml: Polonium INF: Polonium debug is DISABLED! Enable it and restart KWin before sending logs!
Mar 07 12:08:57 HoldenComputer kwin_wayland[6982]: qml: Polonium INF: Polonium started!
Mar 07 12:08:57 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Config is {"debug":true,"tilePopups":false,"filterProcess":["krunner","yakuake","kded","polkit","plasmashell"],"filterCaption":[""],"timerDelay":10,"keepTiledBelow":true,"borders":3,"maximizeSingle":false,"resizeAmount":10,"engineType":1,"insertionPoint":1,"rotateLayout":true}
Mar 07 12:08:58 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Restarting init timer
Mar 07 12:08:58 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Restarting init timer
Mar 07 12:08:58 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Creating new engine for desktop {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:08:58 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Creating new engine for desktop {"desktop":"f8fe0eb9-a399-424d-baa9-e6b87efc4869","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:08:58 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Creating new engine for desktop {"desktop":"0713e37a-1b39-4819-b77b-6be053604e45","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:08:58 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Creating new engine for desktop {"desktop":"ee0d1978-d15d-487b-9a1f-076b7a059e68","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:08:58 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Creating new engine for desktop {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"1e47fa1d-47c9-4e36-b255-dc4afad663de","output":"DP-1"}
Mar 07 12:08:58 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Creating new engine for desktop {"desktop":"f8fe0eb9-a399-424d-baa9-e6b87efc4869","activity":"1e47fa1d-47c9-4e36-b255-dc4afad663de","output":"DP-1"}
Mar 07 12:08:58 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Creating new engine for desktop {"desktop":"0713e37a-1b39-4819-b77b-6be053604e45","activity":"1e47fa1d-47c9-4e36-b255-dc4afad663de","output":"DP-1"}
Mar 07 12:08:58 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Creating new engine for desktop {"desktop":"ee0d1978-d15d-487b-9a1f-076b7a059e68","activity":"1e47fa1d-47c9-4e36-b255-dc4afad663de","output":"DP-1"}
Mar 07 12:08:58 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Window plasmashell hooked into script
Mar 07 12:08:58 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Not tiling window plasmashell
Mar 07 12:08:58 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Window ksplashqml removed
Mar 07 12:08:58 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Removing client ksplashqml from desktops
Mar 07 12:08:58 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:08:59 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Window plasmashell hooked into script
Mar 07 12:08:59 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Not tiling window plasmashell
Mar 07 12:08:59 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Window plasmashell hooked into script
Mar 07 12:08:59 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Not tiling window plasmashell
Mar 07 12:08:59 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Window firefox hooked into script
Mar 07 12:08:59 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Window firefox added
Mar 07 12:08:59 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Adding client firefox to desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:08:59 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:08:59 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Window thunderbird hooked into script
Mar 07 12:08:59 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Window thunderbird added
Mar 07 12:08:59 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Adding client thunderbird to desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:08:59 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:08:59 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Removing client firefox from desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:08:59 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Adding client firefox to desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:08:59 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:00 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Window firefox hooked into script
Mar 07 12:09:00 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Window firefox added
Mar 07 12:09:00 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Adding client firefox to desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:00 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:00 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Removing client firefox from desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:00 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Adding client firefox to desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:00 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:00 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Removing client firefox from desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:00 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Adding client firefox to desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:00 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:04 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Client firefox was moved out of a tile
Mar 07 12:09:04 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Removing client firefox from desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:04 HoldenComputer kwin_wayland[6982]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:05 HoldenComputer kwin_wayland[8075]: qml: Polonium INF: Polonium started!
Mar 07 12:09:05 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Config is {"debug":true,"tilePopups":false,"filterProcess":["krunner","yakuake","kded","polkit","plasmashell"],"filterCaption":[""],"timerDelay":10,"keepTiledBelow":true,"borders":3,"maximizeSingle":false,"resizeAmount":10,"engineType":1,"insertionPoint":1,"rotateLayout":true}
Mar 07 12:09:06 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Creating new engine for desktop {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:06 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Creating new engine for desktop {"desktop":"f8fe0eb9-a399-424d-baa9-e6b87efc4869","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:06 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Creating new engine for desktop {"desktop":"0713e37a-1b39-4819-b77b-6be053604e45","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:06 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Creating new engine for desktop {"desktop":"ee0d1978-d15d-487b-9a1f-076b7a059e68","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:06 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Creating new engine for desktop {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"1e47fa1d-47c9-4e36-b255-dc4afad663de","output":"DP-1"}
Mar 07 12:09:06 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Creating new engine for desktop {"desktop":"f8fe0eb9-a399-424d-baa9-e6b87efc4869","activity":"1e47fa1d-47c9-4e36-b255-dc4afad663de","output":"DP-1"}
Mar 07 12:09:06 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Creating new engine for desktop {"desktop":"0713e37a-1b39-4819-b77b-6be053604e45","activity":"1e47fa1d-47c9-4e36-b255-dc4afad663de","output":"DP-1"}
Mar 07 12:09:06 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Creating new engine for desktop {"desktop":"ee0d1978-d15d-487b-9a1f-076b7a059e68","activity":"1e47fa1d-47c9-4e36-b255-dc4afad663de","output":"DP-1"}
Mar 07 12:09:06 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Window crashreporter hooked into script
Mar 07 12:09:06 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Window crashreporter added
Mar 07 12:09:06 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Adding client crashreporter to desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:06 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:06 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Window plasmashell hooked into script
Mar 07 12:09:06 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Not tiling window plasmashell
Mar 07 12:09:06 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Window plasmashell hooked into script
Mar 07 12:09:06 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Not tiling window plasmashell
Mar 07 12:09:07 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Window plasmashell hooked into script
Mar 07 12:09:07 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Not tiling window plasmashell
Mar 07 12:09:10 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Window systemsettings hooked into script
Mar 07 12:09:10 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Window systemsettings added
Mar 07 12:09:10 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Adding client systemsettings to desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:10 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:12 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Window systemsettings removed
Mar 07 12:09:12 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Removing client systemsettings from desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:12 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:15 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Window firefox hooked into script
Mar 07 12:09:15 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Window firefox added
Mar 07 12:09:15 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Adding client firefox to desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:15 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:15 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Removing client firefox from desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:15 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Adding client firefox to desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:15 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:15 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Window crashreporter removed
Mar 07 12:09:15 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Removing client crashreporter from desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:15 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:16 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Window firefox hooked into script
Mar 07 12:09:16 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Not tiling window firefox
Mar 07 12:09:17 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Window firefox removed
Mar 07 12:09:17 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Removing client firefox from desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:17 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:17 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Removing client firefox from desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:17 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Adding client firefox to desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:17 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:17 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Removing client firefox from desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:17 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Adding client firefox to desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:17 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:21 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Window org.kde.yakuake hooked into script
Mar 07 12:09:21 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Not tiling window org.kde.yakuake
Mar 07 12:09:39 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Window org.kde.yakuake removed
Mar 07 12:09:39 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Removing client org.kde.yakuake from desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:39 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"e6fa73cb-218a-4028-a2bf-3b6715735e20","activity":"69113cd0-bb6d-453e-b0ae-ce5b6e01c928","output":"DP-1"}
Mar 07 12:09:40 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Window org.kde.yakuake hooked into script
Mar 07 12:09:40 HoldenComputer kwin_wayland[8075]: qml: Polonium DBG: Not tiling window org.kde.yakuake
```

**Comment by FantasyPvP** [comment] 2024-03-08 19:16
pretty sure this is a duplicate of #107 apparently it's a kwin bug. I've been getting this issue too. it seems like polonium isn't going to be usable on plasma 6 until it gets fixed upstream

**Closed** 2024-03-27 20:08 UTC
Labels: bug
