### ISSUE TITLE
Vivaldi does not tile (when ran as a xwayland app (default)) [Bug]: 

### ISSUE THREAD

**Issue by zany130** [zeroxoneafour/polonium#140] opened 2024-04-03 20:33 UTC
### Before you make the issue, confirm that

- [X] You are running the master build from GitHub actions
- [X] You have read the FAQ and the usage instructions
- [X] You have searched pull requests and issues and have found none similar to your issue
- [X] This problem comes from a failure in the tiling system and not a missing feature

### Describe the bug

Vivaldi does not tile alongside other tiled windows. Opens Maximised on top of other tiled windows.

### To reproduce

1. Launch a termnial or any window
2. Launch vivaldi
3. notice vivaldi does not get tiledNotice Vivaldi

### Expected behavior

Vivaldi gets tiled alongside other windows	

### Relevant log output

```shell
journalctl --user --no-pager -e | grep -i "polonium"
Apr 03 16:31:46 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window org.kde.plasmashell hooked into script
Apr 03 16:31:46 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Not tiling window org.kde.plasmashell
Apr 03 16:31:46 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window org.kde.plasmashell hooked into script
Apr 03 16:31:46 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Not tiling window org.kde.plasmashell
Apr 03 16:31:47 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window org.kde.plasmashell hooked into script
Apr 03 16:31:47 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Not tiling window org.kde.plasmashell
Apr 03 16:31:49 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window steam hooked into script
Apr 03 16:31:49 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window steam added
Apr 03 16:31:49 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Adding window steam to desktops {"desktop":"8d5382aa-d8b0-416b-8148-ec30b5b4dfc5","activity":"f577afb5-1dac-4cd8-932c-770f8518f05f","output":"DP-2"}
Apr 03 16:31:49 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"8d5382aa-d8b0-416b-8148-ec30b5b4dfc5","activity":"f577afb5-1dac-4cd8-932c-770f8518f05f","output":"DP-1"},{"desktop":"8d5382aa-d8b0-416b-8148-ec30b5b4dfc5","activity":"f577afb5-1dac-4cd8-932c-770f8518f05f","output":"DP-2"},{"desktop":"8d5382aa-d8b0-416b-8148-ec30b5b4dfc5","activity":"f577afb5-1dac-4cd8-932c-770f8518f05f","output":"HDMI-A-2"}
Apr 03 16:31:49 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Fullscreen on client steam set to true
Apr 03 16:31:49 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Untiling window steam on desktops {"desktop":"8d5382aa-d8b0-416b-8148-ec30b5b4dfc5","activity":"f577afb5-1dac-4cd8-932c-770f8518f05f","output":"DP-2"}
Apr 03 16:31:49 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"8d5382aa-d8b0-416b-8148-ec30b5b4dfc5","activity":"f577afb5-1dac-4cd8-932c-770f8518f05f","output":"DP-2"}
Apr 03 16:31:54 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window TeamViewer hooked into script
Apr 03 16:31:54 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window TeamViewer added
Apr 03 16:31:54 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Adding window TeamViewer to desktops {"desktop":"8d5382aa-d8b0-416b-8148-ec30b5b4dfc5","activity":"f577afb5-1dac-4cd8-932c-770f8518f05f","output":"DP-1"}
Apr 03 16:31:54 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"8d5382aa-d8b0-416b-8148-ec30b5b4dfc5","activity":"f577afb5-1dac-4cd8-932c-770f8518f05f","output":"DP-1"},{"desktop":"8d5382aa-d8b0-416b-8148-ec30b5b4dfc5","activity":"f577afb5-1dac-4cd8-932c-770f8518f05f","output":"DP-2"},{"desktop":"8d5382aa-d8b0-416b-8148-ec30b5b4dfc5","activity":"f577afb5-1dac-4cd8-932c-770f8518f05f","output":"HDMI-A-2"}
Apr 03 16:32:11 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window org.kde.plasmashell removed
Apr 03 16:32:11 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Removing window org.kde.plasmashell from desktops
Apr 03 16:32:13 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window org.kde.plasmashell hooked into script
Apr 03 16:32:13 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Not tiling window org.kde.plasmashell
Apr 03 16:32:14 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window vivaldi-stable hooked into script
Apr 03 16:32:14 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window vivaldi-stable added
Apr 03 16:32:14 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Adding window vivaldi-stable to desktops
Apr 03 16:32:14 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"8d5382aa-d8b0-416b-8148-ec30b5b4dfc5","activity":"f577afb5-1dac-4cd8-932c-770f8518f05f","output":"DP-1"},{"desktop":"8d5382aa-d8b0-416b-8148-ec30b5b4dfc5","activity":"f577afb5-1dac-4cd8-932c-770f8518f05f","output":"DP-2"},{"desktop":"8d5382aa-d8b0-416b-8148-ec30b5b4dfc5","activity":"f577afb5-1dac-4cd8-932c-770f8518f05f","output":"HDMI-A-2"}
Apr 03 16:32:14 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window vivaldi-stable hooked into script
Apr 03 16:32:14 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window vivaldi-stable added
Apr 03 16:32:14 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Adding window vivaldi-stable to desktops
Apr 03 16:32:14 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"8d5382aa-d8b0-416b-8148-ec30b5b4dfc5","activity":"f577afb5-1dac-4cd8-932c-770f8518f05f","output":"DP-1"},{"desktop":"8d5382aa-d8b0-416b-8148-ec30b5b4dfc5","activity":"f577afb5-1dac-4cd8-932c-770f8518f05f","output":"DP-2"},{"desktop":"8d5382aa-d8b0-416b-8148-ec30b5b4dfc5","activity":"f577afb5-1dac-4cd8-932c-770f8518f05f","output":"HDMI-A-2"}
Apr 03 16:32:14 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window org.kde.plasmashell removed
Apr 03 16:32:14 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Removing window org.kde.plasmashell from desktops
Apr 03 16:32:14 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window org.kde.plasmashell removed
Apr 03 16:32:14 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Removing window org.kde.plasmashell from desktops
Apr 03 16:32:14 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window org.kde.plasmashell hooked into script
Apr 03 16:32:14 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Not tiling window org.kde.plasmashell
Apr 03 16:32:14 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window org.kde.plasmashell removed
Apr 03 16:32:14 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Removing window org.kde.plasmashell from desktops
Apr 03 16:32:15 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window org.kde.plasmashell hooked into script
Apr 03 16:32:15 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Not tiling window org.kde.plasmashell
Apr 03 16:32:15 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window org.kde.plasmashell removed
Apr 03 16:32:15 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Removing window org.kde.plasmashell from desktops
Apr 03 16:32:16 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window org.kde.plasmashell removed
Apr 03 16:32:16 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Removing window org.kde.plasmashell from desktops
Apr 03 16:32:16 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window org.kde.plasmashell hooked into script
Apr 03 16:32:16 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Not tiling window org.kde.plasmashell
Apr 03 16:32:17 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window org.kde.plasmashell hooked into script
Apr 03 16:32:17 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Not tiling window org.kde.plasmashell
Apr 03 16:32:18 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window org.kde.plasmashell removed
Apr 03 16:32:18 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Removing window org.kde.plasmashell from desktops
Apr 03 16:32:19 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window TeamViewer removed
Apr 03 16:32:19 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Removing window TeamViewer from desktops {"desktop":"8d5382aa-d8b0-416b-8148-ec30b5b4dfc5","activity":"f577afb5-1dac-4cd8-932c-770f8518f05f","output":"DP-1"}
Apr 03 16:32:19 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"8d5382aa-d8b0-416b-8148-ec30b5b4dfc5","activity":"f577afb5-1dac-4cd8-932c-770f8518f05f","output":"DP-1"},{"desktop":"8d5382aa-d8b0-416b-8148-ec30b5b4dfc5","activity":"f577afb5-1dac-4cd8-932c-770f8518f05f","output":"DP-2"},{"desktop":"8d5382aa-d8b0-416b-8148-ec30b5b4dfc5","activity":"f577afb5-1dac-4cd8-932c-770f8518f05f","output":"HDMI-A-2"}
Apr 03 16:32:20 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window org.kde.plasmashell removed
Apr 03 16:32:20 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Removing window org.kde.plasmashell from desktops
Apr 03 16:32:21 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window python3 removed
Apr 03 16:32:21 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Removing window python3 from desktops {"desktop":"8d5382aa-d8b0-416b-8148-ec30b5b4dfc5","activity":"f577afb5-1dac-4cd8-932c-770f8518f05f","output":"DP-1"}
Apr 03 16:32:21 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Rebuilding layout for desktops {"desktop":"8d5382aa-d8b0-416b-8148-ec30b5b4dfc5","activity":"f577afb5-1dac-4cd8-932c-770f8518f05f","output":"DP-1"},{"desktop":"8d5382aa-d8b0-416b-8148-ec30b5b4dfc5","activity":"f577afb5-1dac-4cd8-932c-770f8518f05f","output":"DP-2"},{"desktop":"8d5382aa-d8b0-416b-8148-ec30b5b4dfc5","activity":"f577afb5-1dac-4cd8-932c-770f8518f05f","output":"HDMI-A-2"}
Apr 03 16:32:21 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Window org.kde.plasmashell removed
Apr 03 16:32:21 Garuda-Linux kwin_wayland[8630]: qml: Polonium DBG: Removing window org.kde.plasmashell from desktops
```

**Comment by zeroxoneafour** [comment] 2024-04-04 01:21
It appears that vivaldi sets itself to be a maximized window if it was previously maximized and then closed. The issue is that, unlike most windows that do this (discord, firefox, dolphin etc.) Vivaldi does this after it is opened and not during the opening process. This causes the maximization to be picked up as a user action and leads to Vivaldi becoming untiled.

There are a few solutions -
1. Disable "maximize when single window" and tile/float Vivaldi, then close it. Vivaldi shouldn't remember being maximized and should stay manipulatable by the engine.
2. Tile Vivaldi if it starts maximized, this can be done in a variety of ways. The untile/retile shortcut is most likely the best way, but the maximize/unmaximize shortcut can be used as well (just swap desktops quickly to rebuild the layout)
3. Disable remembering window state for Vivaldi, I wouldn't know how to do this but I assume it's possible somehow.

Try one of these solutions and see how it works for you. There will never be a fix to the root cause of this issue unless Vivaldi chooses to not start maximized.

**Comment by zany130** [comment] 2024-04-04 16:03
Hmm no luck vivaldi just seems to ignore the untile/retile shortcut (other apps work fine with it)

I tried setting some window rules to disable initial placement of the vivaldi window but all that does is open vivaldi floating un maximised 
![image](https://github.com/zeroxoneafour/polonium/assets/25832539/18dfff54-70a8-4a3b-9ae8-522d1916ed5a)

**Comment by zany130** [comment] 2024-04-16 23:33
appernetly enabling wayland support fixes the issue. you can do that by setting `vivaldi://flags/#ozone-platform-hint` to auto or wayland. Vivaldi now tiles with the rest of my windows

**Comment by zeroxoneafour** [comment] 2024-04-19 02:54
To be fair, if the app runs fine on Wayland and X11 is not officially supported, this issue might as well be resolved.

**Closed by zeroxoneafour** 2024-04-19 02:54 UTC
Labels: bug

**Comment by zany130** [comment] 2024-04-20 00:25
one caveat is this doesn't solve the problem 100% it still fails to tile I have manually occasionally grabbed it and tiled it by moving it to the the screen edge sometimes to kick in ill try to get a log of this

**Comment by zany130** [comment] 2024-04-28 20:47
@zeroxoneafour tiling seems to have broken on Vivaldi again my previous fix of manually tiling with the mouse no longer works polonium tiles windows behind Vivaldi its as if Vivaldi does not exist for Polonium 

tried to get a log but polonium for some reason is no longer outputting to the journal 
`journalctl --user --no-pager -e | grep -i "polonium"`

doesn't show anything I have left logging enabled in the polonium settings
