### ISSUE TITLE
[Bug]: Polonium many times lost Windows state & current kde tiling state

### ISSUE THREAD

**Issue by Maziar123** [zeroxoneafour/polonium#85] opened 2023-09-06 08:00 UTC
### Before you make the issue, confirm that

- [X] You are running the master build from GitHub actions
- [X] You have read the FAQ and the usage instructions
- [X] You have searched pull requests and issues and have found none similar to your issue
- [X] This problem comes from a failure in the tiling system and not a missing feature

### Describe the bug

Btree does not rebuild sometimes when all windows close.

1.I open some windows and float it  & move it close.(then not any windows open)

2. Now open two windows again: see what happens: 

![Screenshot_20230906_111820](https://github.com/zeroxoneafour/polonium/assets/6292459/16db4615-7564-44d1-86c7-261e0c7aa42e)

In the pic, no tiling happens. It seems after closing windows, polonium lost its current state!

3. See KDE tiling state with zombies:
![Screenshot_20230906_111913](https://github.com/zeroxoneafour/polonium/assets/6292459/fe350fab-c4a4-4fa3-9421-aaa4027d3bd7)

### To reproduce

as commented in the upcoming

### Expected behavior

The Expected behavior works btree true. 
Code practice is current tiling wm such as sway, dmw,hyprland &...

### Relevant log output

```shell
picture sended
```

**Comment by zeroxoneafour** [comment] 2023-09-08 03:31
99% chance a duplicate of #84

**Closed by zeroxoneafour** 2023-09-08 03:31 UTC
Labels: bug, needs log
