### ISSUE TITLE
Drag windows between tiles

### ISSUE THREAD

**Issue by rhopp** [zeroxoneafour/polonium#87] opened 2023-09-26 08:43 UTC
**Is your feature request related to a problem? Please describe.**
In my flow of work I often move windows around between tiles (and between monitors as well) by dragging the windows (by pressing modifier key (Meta by default) + left mouse button dragging). Moving one window to the place of other window (tile) would just swap those windows between the tiles.
Example: Tile 1 is occupied by Window 1. Tile 2 is occupied by Window 2. Dragging Window 2 (by title bar or modifier key + left mouse button) on top of Tile1/Window1 would result in: Tile 1 occupied by Window 2, Tile 2 occupied by Window 1.

**Describe the solution you'd like**
Dragging windows between tiles would work - it would swap the two windows in those two tiles affected. Currently, dragging the window just de-tiles the window.

**Describe alternatives you've considered**
none?

**Additional context**

**Comment by zeroxoneafour** [comment] 2023-09-26 15:59
Duplicate of #25 and addressed heavily in the [v0.5.1 release notes](https://github.com/zeroxoneafour/polonium/releases/tag/v0.5.1), this feature will likely never be supported.

**Closed by zeroxoneafour** 2023-09-26 16:00 UTC
Labels: enhancement
