### ISSUE TITLE
Ability to rotate layouts

### ISSUE THREAD

**Issue by ItMeCorban** [zeroxoneafour/polonium#168] opened 2024-05-13 10:23 UTC
I use a vertical monitor for messaging/email apps. I usually split it halfway and have one app on top, one on bottom. It would be handy to be able to rotate the layouts so that this can be done with auto tiling. This was a feature in both Krohnkite and Bismuth previously

**Comment by pjhfggij** [comment] 2024-05-13 22:54
Duplicate of #68 

> This was a feature in both Krohnkite and Bismuth previously

It was and it was great - I miss these times a lot, but they will never return. Ever since that faithful day when KWin announced their breaking of the API. I still remember that day. The sky was dark and the leaves were gently flowing on a cold wind...

**Comment by zeroxoneafour** [comment] 2024-05-14 05:28
@pjhfggij Khronkite has been updated for v6.0, no? This project has been made to build autotiling off of KWin's integrated tiling system. Adapting highly complex tiling scripts to what basically amounts to Windows Powertoys is going to come with some loss of functionality. On my end, this is often inexplicable and requires sometimes extreme workarounds. For advanced tiling, I can highly recommend Khronkite as it is built to support more complex layouts.

Anyways, yes, this is basically a word for word duplicate of a highly active issue from like half a year ago.

**Closed by zeroxoneafour** 2024-05-14 05:28 UTC
Labels: enhancement

**Comment by pjhfggij** [comment] 2024-05-15 00:03
Part of me knows that this was force majourne an simply accepts this faith, but another part has to live with [this](https://github.com/zeroxoneafour/polonium/issues/168). Don't mind me at all, you were the person who stepped up and maintained the only viable tiling alternative when the night was the darkest. Thank you very much.

I've had no idea Kronkhite is back. That sounds great. I did have some problems with it in the past, bismuth was the perfect solution, but I will try nonetheless. Thank you again for mentioning it and for your work on polonium.
