### ISSUE TITLE
Polonium can crash kwin_wayland if firefox or chromium is dragged between displays

### ISSUE THREAD

**Issue by Managor** [zeroxoneafour/polonium#56] opened 2023-07-03 14:27 UTC
Polonium version: 9b7eb547b15e17cd1cc9a2cd7bf80674d29c645d
Not really a bug for you but a heads up that this can happen
https://bugs.kde.org/show_bug.cgi?id=471867

When doing this doesn't crash, it lags the system immensely which probably is your bug. I'll have to take a look at it once the crash is eventually dealt with.

**Comment by zeroxoneafour** [comment] 2023-07-22 08:12
Is it possible to get a full debug log when this happens?

**Comment by Managor** [comment] 2023-07-29 18:08
[polonium.txt](https://github.com/zeroxoneafour/polonium/files/12207723/polonium.txt)
Wasn't entirely sure what the proper way to get debug logs for this are so I just piped `journalctl -f` to a file inside a tmux session

**Comment by zeroxoneafour** [comment] 2023-07-29 18:45
This is appearing to be another instance of #9. The issue was never fully resolved, and the crashes can still occur sometimes. It has also been marked as a duplicate of the KWin bug reported in #9 on the KWin bug tracker.

When you got the debug log, you did get the output for the session where the crash occurred, right? There is no log output from Polonium before the crash.

**Closed** 2024-03-30 17:15 UTC
Labels: bug, kwin bug, old

**Comment by Managor** [comment] 2024-03-30 17:41
Thanks for reminding me. The crash no longer happens.
