### ISSUE TITLE
How does it work in dual monitor? seems wrong

### ISSUE THREAD

**Issue by Maziar123** [zeroxoneafour/polonium#84] opened 2023-09-05 10:37 UTC
I have the dual monitor (or multi-monitor) and think tiling must understand what location must add new windows similar to i3, sway, or hyprland... by screen with the mouse position.

Also, moving windows to other screens (by mouse or shortcut) seems tiling fails to be tiling comparison sway or hyprland

**Comment by zeroxoneafour** [comment] 2023-09-05 10:57
KWin determines where new windows are placed, not the script. The script should just tile them wherever they are. For the behavior when moving between desktops, that seems like it could be a bug. Could you provide more detail and a log?

**Comment by Maziar123** [comment] 2023-09-05 11:05
Yes, kwin selects, BUT when kwin follows the mouse for new windows  tiling, complimentary wrong 

Can you try it to see what happens?

**Comment by zeroxoneafour** [comment] 2023-09-05 21:44
Just a more thorough explanation of the issue would be fine for now, try giving information similar to the bug report template

**Comment by Maziar123** [comment] 2023-09-06 07:37
Many problems. Some  reproducible for me :

I use  Arch Linux & my current setting :
![Screenshot_20230906_105601](https://github.com/zeroxoneafour/polonium/assets/6292459/dd2fd4e7-468d-4a59-a805-d84589071ee4)

1. I added two windows on the left monitor(primary monitor) many times; moving one to the left monitor kills all open apps!

2. I set kde to new window open in monitor following my mouse. opening in the next monitor, not tiling 

4. Sometimes, rebuild shortcuts fix similar problems & some do not fix them!
   
5. checking kde native tiling with suprt+t in the next monitor shows many zombie regions in the write monitor!


I think this plugin  must be rewritten to understand tiling **per monitor accurately**

**Comment by zeroxoneafour** [comment] 2023-09-08 03:29
> kills all open apps!

The script has no code in it that would allow it to kill open apps. Probably a deeper error in KWin, they seem to be fairly common.

> opening in the next monitor, many times not tiling

If you mean the windows are moved to the next monitor and are placed incorrectly, the script afaik doesn't control that either. A log would be helpful here for sure, again a hard requirement in the bug report template.

> I think this plugin must be rewritten to understand tiling per monitor accurately

Feel free to rewrite it, PRs are open :wink:

**Comment by Maziar123** [comment] 2023-09-08 16:23
I see core dump randomly in two different systems. One of them:

```
Sep 08 19:45:50 mz-tr4b kernel: kwin_wayland[1725]: segfault at 131 ip 00007feedeec25f6 sp 00007fff6e4dcce8 error 4 in libQt5Core.so.5.15.10[7feedec9f000+2dd000] likely on CPU 63 (core 31, socket 0)
Sep 08 19:45:50 mz-tr4b kernel: Code: c0 75 ee 48 83 c4 08 31 c0 5b 5d c3 b8 ff ff ff ff eb c1 90 f3 0f 1e fa 48 8b 47 40 48 85 c0 74 4b 48 8b 48 08 48 85 c9 74 42 <48> 8b 79 10 ba 01 00 00 00 48 85 ff 75 36 48 8b 50 08 48 85 d2 74
Sep 08 19:45:50 mz-tr4b systemd[1]: Created slice Slice /system/systemd-coredump.
Sep 08 19:45:50 mz-tr4b systemd[1]: Started Process Core Dump (PID 24391/UID 0).
Sep 08 19:45:51 mz-tr4b systemd-coredump[24392]: [🡕] Process 1725 (kwin_wayland) of user 1000 dumped core.
                                                 
                                                 Stack trace of thread 1725:
                                                 #0  0x00007feedeec25f6 _ZNK14QObjectPrivate20maybeSignalConnectedEj (libQt5Core.so.5 + 0x2c25f6)
                                                 #1  0x00007feedeed0f3f n/a (libQt5Core.so.5 + 0x2d0f3f)
                                                 #2  0x00007feee08c64df _ZN4KWin10CustomTile19setRelativeGeometryERK6QRectF (libkwin.so.5 + 0x2c64df)
                                                 #3  0x00007feee08c6326 _ZN4KWin10CustomTile19setRelativeGeometryERK6QRectF (libkwin.so.5 + 0x2c6326)
                                                 #4  0x00007feee08c52e7 _ZN4KWin10CustomTile6removeEv (libkwin.so.5 + 0x2c52e7)
                                                 #5  0x00007feee08ca103 _ZN4KWin10CustomTile11qt_metacallEN11QMetaObject4CallEiPPv (libkwin.so.5 + 0x2ca103)
                                                 #6  0x00007feedfc784b4 n/a (libQt5Qml.so.5 + 0x2784b4)
                                                 #7  0x00007feedfb77e96 n/a (libQt5Qml.so.5 + 0x177e96)
                                                 #8  0x00007feedfb7def6 _ZNK3QV413QObjectMethod12callInternalEPKNS_5ValueES3_i (libQt5Qml.so.5 + 0x17def6)
                                                 #9  0x00007feedfba107e _ZN3QV47Runtime18CallPropertyLookup4callEPNS_15ExecutionEngineERKNS_5ValueEjPS4_i (libQt5Qml.so.5 + 0x1a107e)
                                                 #10 0x00007feea80aa341 n/a (n/a + 0x0)
                                                 #11 0x00007feedfb952bd n/a (libQt5Qml.so.5 + 0x1952bd)
                                                 #12 0x00007feedfb372a0 n/a (libQt5Qml.so.5 + 0x1372a0)
                                                 #13 0x00007feedfba107e _ZN3QV47Runtime18CallPropertyLookup4callEPNS_15ExecutionEngineERKNS_5ValueEjPS4_i (libQt5Qml.so.5 + 0x1a107e)
                                                 #14 0x00007fee92ed886d n/a (n/a + 0x0)
                                                 #15 0x00007feedfb952bd n/a (libQt5Qml.so.5 + 0x1952bd)
                                                 #16 0x00007feedfb372a0 n/a (libQt5Qml.so.5 + 0x1372a0)
                                                 #17 0x00007feedfba6e50 _ZN3QV47Runtime9CallValue4callEPNS_15ExecutionEngineERKNS_5ValueEPS4_i (libQt5Qml.so.5 + 0x1a6e50)
                                                 #18 0x00007feea8db06d7 n/a (n/a + 0x0)
                                                 #19 0x00007feedfb952bd n/a (libQt5Qml.so.5 + 0x1952bd)
                                                 #20 0x00007feedfb372a0 n/a (libQt5Qml.so.5 + 0x1372a0)
                                                 #21 0x00007feedfba6e50 _ZN3QV47Runtime9CallValue4callEPNS_15ExecutionEngineERKNS_5ValueEPS4_i (libQt5Qml.so.5 + 0x1a6e50)
                                                 #22 0x00007feea8dbf186 n/a (n/a + 0x0)
                                                 #23 0x00007feedfb952bd n/a (libQt5Qml.so.5 + 0x1952bd)
                                                 #24 0x00007feedfb372a0 n/a (libQt5Qml.so.5 + 0x1372a0)
                                                 #25 0x00007feedfb77713 n/a (libQt5Qml.so.5 + 0x177713)
                                                 #26 0x00007feedeed1637 n/a (libQt5Core.so.5 + 0x2d1637)
                                                 #27 0x00007feee090184c _ZN4KWin6Window20frameGeometryChangedEPS0_RK6QRectF (libkwin.so.5 + 0x30184c)
                                                 #28 0x00007feee0941cef _ZN4KWin9X11Window18moveResizeInternalERK6QRectFNS_6Window14MoveResizeModeE (libkwin.so.5 + 0x341cef)
                                                 #29 0x00007feee08ff34b _ZN4KWin6Window12sendToOutputEPNS_6OutputE (libkwin.so.5 + 0x2ff34b)
                                                 #30 0x00007feedeed1637 n/a (libQt5Core.so.5 + 0x2d1637)
                                                 #31 0x00007feede56bbb7 _ZN7QAction9triggeredEb (libQt5Widgets.so.5 + 0x16bbb7)
                                                 #32 0x00007feede57160b _ZN7QAction8activateENS_11ActionEventE (libQt5Widgets.so.5 + 0x17160b)
                                                 #33 0x00007feedeed1637 n/a (libQt5Core.so.5 + 0x2d1637)
                                                 #34 0x00007feedf8b21ad n/a (libKF5GlobalAccel.so.5 + 0x161ad)
                                                 #35 0x00007feedf8b25e3 n/a (libKF5GlobalAccel.so.5 + 0x165e3)
                                                 #36 0x00007feee0cbd76e n/a (libQt5DBus.so.5 + 0x2176e)
                                                 #37 0x00007feedeec4174 _ZN7QObject5eventEP6QEvent (libQt5Core.so.5 + 0x2c4174)
                                                 #38 0x00007feede57893f _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x17893f)
                                                 #39 0x00007feedee9c6f8 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x29c6f8)
                                                 #40 0x00007feedeea165b _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt5Core.so.5 + 0x2a165b)
                                                 #41 0x00007feedeeeae27 _ZN20QEventDispatcherUNIX13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2eae27)
                                                 #42 0x000055599cd15ba2 n/a (kwin_wayland + 0x134ba2)
                                                 #43 0x00007feedee9b404 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x29b404)
                                                 #44 0x00007feedee9c8a3 _ZN16QCoreApplication4execEv (libQt5Core.so.5 + 0x29c8a3)
                                                 #45 0x000055599cc312fb n/a (kwin_wayland + 0x502fb)
                                                 #46 0x00007feeddc27cd0 n/a (libc.so.6 + 0x27cd0)
                                                 #47 0x00007feeddc27d8a __libc_start_main (libc.so.6 + 0x27d8a)
                                                 #48 0x000055599cc32ed5 n/a (kwin_wayland + 0x51ed5)
                                                 
                                                 Stack trace of thread 1766:
                                                 #0  0x00007feeddc894ae n/a (libc.so.6 + 0x894ae)
                                                 #1  0x00007feeddc8bd40 pthread_cond_wait (libc.so.6 + 0x8bd40)
                                                 #2  0x00007feed1ec782c n/a (radeonsi_dri.so + 0xc782c)
                                                 #3  0x00007feed1f1473c n/a (radeonsi_dri.so + 0x11473c)
                                                 #4  0x00007feeddc8c9eb n/a (libc.so.6 + 0x8c9eb)
                                                 #5  0x00007feeddd10dfc n/a (libc.so.6 + 0x110dfc)
                                                 
                                                 Stack trace of thread 1756:
                                                 #0  0x00007feeddd0359f __poll (libc.so.6 + 0x10359f)
                                                 #1  0x00007feedc76db8f n/a (libglib-2.0.so.0 + 0xb7b8f)
                                                 #2  0x00007feedc70e112 g_main_context_iteration (libglib-2.0.so.0 + 0x58112)
                                                 #3  0x00007feedeeeb51c _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2eb51c)

```

**Comment by zeroxoneafour** [comment] 2023-09-08 16:44
Kwin crashes imo will never be the scripts fault, as these edge cases should be handled within Kwin. This is shaping up to be another setRelativeGeometry bug (duplicate of #9, bug report [here](https://bugs.kde.org/show_bug.cgi?id=470759)) if no new information comes to light.

**Closed** 2024-04-03 13:29 UTC
Labels: bug, needs log, old
